spring:
  profiles:
    active: dev
---
# DataSource Config
spring:
  profiles: dev
  datasource:
    name: sampleDs
    url:
      jdbc:mysql://localhost:3306/glaner_core?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: rlan123
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml


# Logger Config
logging:
  level:
    com.lank.demo: debug